// File to store all Colors, for central editing

// Colors & Fonts
var TEAL = '#2a8985'; 
var PURPLE = '#9068be';
var RED = '#e62739';
var HEADER_RED = '#e14755';
var FONT = 'Avenir Next';
var MAX_SLIDER_COLOR = '#d3d3d3';
var MIN_SLIDER_COLOR = '#9068be';
var SLIDER_THUMB_COLOR = '#9068be';
var INACTIVE_LEFT_TEXT = '#686868';
var INACTIVE_LEFT_BUBBLE = '#f0f0f0';
var INACTIVE_RIGHT_TEXT = '#686868';
var INACTIVE_RIGHT_BUBBLE = '#C0C0C0';
var INACTIVE_SEND = '#686868';
var POPUP_BACKGROUND = "#DDDDDD";
var TEXT_INPUT_BORDER = "#BBBBBB";
var TEXT_INPUT_BACKGROUND = "#FFFFFF"; 
var BORDER_COLOR = '#DAD9DC';
var TITLE_UNDERLAY_COLOR = '#F9F9FB';
var DIALOG_TEXT_COLOR = '#7F7D89';


// Things to Color
var HEADER_COLOR = HEADER_RED; 
var HEADER_CONTENT_COLOR = 'white';

var TAB_UNSELECTED_COLOR = 'darkgrey';
var TAB_SELECTED_COLOR = 'white';
var TAB_COLOR = RED; 
var BADGE_COLOR = TEAL;

var DISMISS_COLOR = RED;
var ACCEPT_COLOR = PURPLE;
var BLOCK_COLOR = TEAL;

var BOLD_COLOR = 'black';
var DEFAULT_TEXT_COLOR = '#000000';

var AVATAR_BACKGROUND_COLOR = 'white';

var EDIT_CHAT_NAME_COLOR = PURPLE;
var BLOCK_USER_MENU_COLOR = HEADER_RED;
var REFRESH_MENU_COLOR = TEAL;
var OFFLINE_MENU_COLOR = PURPLE;

var DEACTIVATE_COLOR = RED;

var CHAT_BUBBLE_COLOR = PURPLE;

var LOADING_BACKGROUND = '#F5FCFF88';


export {
	POPUP_BACKGROUND,
	TEXT_INPUT_BACKGROUND,
	TEXT_INPUT_BORDER,
	MAX_SLIDER_COLOR,
	MIN_SLIDER_COLOR,
	SLIDER_THUMB_COLOR,
	HEADER_CONTENT_COLOR,
	HEADER_COLOR,
	TAB_UNSELECTED_COLOR, 
	TAB_SELECTED_COLOR, 
	TAB_COLOR, 
	DISMISS_COLOR, 
	BLOCK_COLOR,
	ACCEPT_COLOR, 
	BOLD_COLOR,
	DEFAULT_TEXT_COLOR,
	AVATAR_BACKGROUND_COLOR,
	EDIT_CHAT_NAME_COLOR,
	BLOCK_USER_MENU_COLOR,
	DEACTIVATE_COLOR,
	FONT,
	BADGE_COLOR,
	CHAT_BUBBLE_COLOR,
	LOADING_BACKGROUND,
	INACTIVE_RIGHT_BUBBLE,
	INACTIVE_RIGHT_TEXT,
	INACTIVE_LEFT_BUBBLE,
	INACTIVE_LEFT_TEXT,
	INACTIVE_SEND,
	REFRESH_MENU_COLOR,
	OFFLINE_MENU_COLOR,
	BORDER_COLOR, 
	TITLE_UNDERLAY_COLOR,
	DIALOG_TEXT_COLOR
};
